apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress-useradata-claim
      containers:
      - name: wordpress
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
